### ISSUE TITLE
Error on viewing a thread.

### ISSUE THREAD

**Issue by bariscodefxy** [Akif9748/akf-forum#2]
I got this error when i try to see a thread.
URL: https://akf-forum.glitch.me/threads/9
```
TypeError: /app/views/thread.ejs:31
    29| 
    30|   <div style="text-align:center;padding:8px">
 >> 31|     <% if ((user.id === thread.authorID || user.admin ) && thread.state !== "DELETED"){ %>
    32|     <a onclick="delete_thread('<%= thread.id %>')" class="btn-outline-primary">DELETE</a>
    33|     <a onclick="edit_thread('<%= thread.id %>')" class="btn-outline-primary">EDIT</a>
    34|     <% } else if (thread.state == "DELETED") { %>

Cannot read properties of null (reading 'id')
    at eval ("/app/views/thread.ejs":35:18)
    at thread (/app/node_modules/ejs/lib/ejs.js:703:17)
    at tryHandleCache (/app/node_modules/ejs/lib/ejs.js:274:36)
    at View.exports.renderFile [as engine] (/app/node_modules/ejs/lib/ejs.js:491:10)
    at View.render (/app/node_modules/express/lib/view.js:135:8)
    at tryRender (/app/node_modules/express/lib/application.js:657:10)
    at Function.render (/app/node_modules/express/lib/application.js:609:3)
    at ServerResponse.render (/app/node_modules/express/lib/response.js:1039:7)
    at ServerResponse.res.reply (/app/index.js:34:14)
    at /app/routes/threads.js:34:13

   ```

**Comment by Akif9748** [comment]
The reason was, not logged in users. i think it is fixed, thanks for reporting. Now we sync with the site.
